### ISSUE TITLE
 java.lang.ClassCastException: class java.time.OffsetDateTime cannot be cast to class java.time.LocalDateTime

### ISSUE THREAD

**Issue by madpoptart** [ical4j/ical4j#748] opened 2024-10-14 14:44 UTC
**Describe the bug**
An incorrect cast is used in the ZoneRulesBuilder class buildDSTTransitions method. The following VTIMEZONE demonstrates the issue. 

**To Reproduce**
Loading a calendar with the following VTIMEZONE definition causes the casting problem: 
```
BEGIN:VTIMEZONE
TZID:US/Central
BEGIN:STANDARD
DTSTART:20070101T000000Z
RRULE:FREQ=YEARLY;WKST=SU;BYMONTH=11;BYDAY=1SU
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20070101T000000Z
RRULE:FREQ=YEARLY;WKST=SU;BYMONTH=3;BYDAY=1SU
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
END:DAYLIGHT
END:VTIMEZONE
```

**Expected behavior**
Calendar parses without exception

**Stacktrace**

```
Caused by: java.lang.ClassCastException: class java.time.OffsetDateTime cannot be cast to class java.time.LocalDateTime (java.time.OffsetDateTime and java.time.LocalDateTime are in module java.base of loader 'bootstrap')
	at net.fortuna.ical4j.model.ZoneRulesBuilder.buildDSTTransitions(ZoneRulesBuilder.java:86)
	at net.fortuna.ical4j.model.ZoneRulesBuilder.build(ZoneRulesBuilder.java:145)
Caused by: java.lang.ClassCastException: class java.time.OffsetDateTime cannot be cast to class java.time.LocalDateTime (java.time.OffsetDateTime and java.time.LocalDateTime are in module java.base of loader 'bootstrap')

	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:158)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:136)
	at net.fortuna.ical4j.data.DefaultContentHandler.endComponent(DefaultContentHandler.java:125)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:449)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:217)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:126)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:188)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:161)
	... 17 more
```

**Environment**
 - OS: Linux 6.10.12-200.fc40.x86_64 x86_64
 - Java Version: temurin-21-jdk
 - iCal4j Version 4.0.4

**Additional context**
Versions prior to 4 did not exhibit the issue. 
The following rewrite "solves" the problem:

```java
/**
     * Build a list of transitions for DST changes. These are typically temporary offset changes every six months.
     *
     * @param observances
     * @return
     */
    private List<ZoneOffsetTransition> buildDSTTransitions(List<Observance> observances) {
        List<ZoneOffsetTransition> transitions = new ArrayList<>();

        for (Observance observance : observances) {
            Optional<TzOffsetFrom> offsetFrom = observance.getTimeZoneOffsetFrom();
            TzOffsetTo offsetTo = observance.getRequiredProperty(Property.TZOFFSETTO);


            // ignore transitions that have no effect..
            if (offsetFrom.isPresent() && !offsetFrom.get().getOffset().equals(offsetTo.getOffset())) {
                DtStart<Temporal> start = observance.getRequiredProperty("DTSTART");

                LocalDateTime startDate;

                if (start.getDate() instanceof java.time.OffsetDateTime) {
                    startDate = ((OffsetDateTime) start.getDate()).toLocalDateTime();
                } else if (start.getDate() instanceof java.time.ZonedDateTime) {
                    startDate = ((ZonedDateTime) start.getDate()).toLocalDateTime();
                } else {
                    startDate = (LocalDateTime) start.getDate();
                }

                LocalDateTime periodEnd = LocalDateTime.now();
                if (periodEnd.isBefore(startDate)) {
                    periodEnd = startDate.plusYears(5);
                }
                observance.calculateRecurrenceSet(new Period<>(startDate, periodEnd))
                        .forEach(p -> {

                            LocalDateTime pStart;

                            if (p.getStart() instanceof OffsetDateTime) {
                                pStart = ((OffsetDateTime) p.getStart()).toLocalDateTime();
                            } else {
                                pStart = (LocalDateTime) p.getStart();
                            }

                            transitions.add(ZoneOffsetTransition.of(pStart,
                                    offsetFrom.get().getOffset(), offsetTo.getOffset()));
                        });
            }
        }
        return transitions;
    }
```

**Comment by benfortuna** [comment] 2024-10-31 23:42
The cause of this error is that `DTSTART` must be specified in local time for `VTIMEZONE` definitions:

```
The mandatory "DTSTART" property gives the effective onset date
      and local time for the time zone sub-component definition.
      "DTSTART" in this usage MUST be specified as a date with a local
      time value.
```

- [RFC5545](https://www.rfc-editor.org/rfc/rfc5545.html#section-3.6.5)

At this stage I wouldn't want to support UTC values in this field, unless there was a compelling reason, so if you are able to update the definitions to comply with the spec that would be the best resolution.

**Comment by madpoptart** [comment] 2024-11-04 22:57
Hi Ben, 
Sorry for the late reply. The notification email was sent to my Junk mail folder.  I'm not sure I fully understand the solution you are proposing. Are you saying update the BEGIN:VTIMEZONE definition in the .ical file? If so that isn't possible as this is a third party calendar system used by a very large number of schools in the country. I don't work for them rather I am tasked with integrating their calendar system and unfortunately this is what it produced.

**Comment by benfortuna** [comment] 2024-11-04 23:21
Hi,

Yeah, so that was my point regarding a compelling reason such as a well-known vendor implementation. 

Are you able to share the name of the software/vendor? Would you have a support channel where you can raise a bug ticket against their iCalendar implementation?

Sometimes we are able to implement a workaround for such non-compliance, but in this case it could result in wrong timezone definitions that could manifest as bugs in your implementation (e.g. events may appear at different times depending on the calendar software).

**Comment by benfortuna** [comment] 2024-11-06 01:23
The previous versions of iCal4j were based on the old Java Date class, which was more lenient in parsing, but also made assumptions about the use of UTC time where the specification doesn't allow for it.

We could make the same assumptions (in relaxed mode), but I want to understand the intention of using UTC time in VTIMEZONE definitions as it could mean:

1. The date is actually in UTC time, it was just derived from the local time of the given timezone, or;
2. The date is actually in local time but formatted incorrectly

For option1 we can parse as is (in relaxed mode), but for option 2 we would remove the `Z` from the string to make it compliant.

**Comment by madpoptart** [comment] 2024-11-06 20:19
In my opinion option 1 makes the most sense. For example in our system we store all dates and times in epoch UTC. I know that isn't the same as the calendar specification, rather an example of someone storing a date in UTC that has already been offset for the timezone. Especially since the idea would be to only have this available in relaxed mode. I still think the exception should at least be caught and re-thrown with better information. I feel a type cast exception could lead to an incorrect interpretation of the error.

**Comment by benfortuna** [comment] 2024-11-11 23:05
Ok I have added support for option 1, will be included in the next release.

**Comment by madpoptart** [comment] 2024-11-12 14:27
Thanks! I think we can close this ticket for now.

**Closed** 2024-11-12 14:27 UTC
