### ISSUE TITLE
 Transitive Library javax.mail causes compatibility issue with jakarta mail with alpha12 version ICAL4j

### ISSUE THREAD

**Issue by leccyril** [ical4j/ical4j#572] opened 2022-05-06 13:32 UTC
**Describe the bug**

The transitive import of javax.mail cause compatibility errors with for example GreenMail server when instanciate POP3Server class

it have been added in build.gradle in last version (alpha11 works, alpha12 not)

in dependencies you added :             'com.sun.mail:javax.mail:1.6.2' (from 2018)

jakarta is the new release since 2019 to use see this : 

_July 3, 2019 - Jakarta Mail is the new name for JavaMail
The JavaMail technology contributed to the Eclipse Foundation has been renamed to “Jakarta Mail” to reflect its role in the [Jakarta EE platform](https://jakarta.ee/)._

**To Reproduce**
1 use last version for ICAL4J (alpha12)
2 use GreenMail server for send mail
3 init and start GreenMail with pop3 instanciation
4 check the error

**Expected behavior**
1. GreenMail have to start correctly
2. ICAL4j have to use last jakarta lib

**Additional context**
```
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
        Suppressed: java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/icegreen/greenmail/pop3/Pop3Server.createStore()Ljakarta/mail/Store; @4: areturn
  Reason:
    Type 'com/sun/mail/pop3/POP3Store' (current frame, stack[0]) is not assignable to 'jakarta/mail/Store' (from method signature)
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'com/icegreen/greenmail/pop3/Pop3Server' }
    stack: { 'com/sun/mail/pop3/POP3Store' }
  Bytecode:
    0000000: 2ab6 000a b0                           

                at com.icegreen.greenmail.util.GreenMail.createServices(GreenMail.java:162)
                at com.icegreen.greenmail.util.GreenMail.init(GreenMail.java:88)
                at com.icegreen.greenmail.util.GreenMail.<init>(GreenMail.java:77)
                at com.seanergie.test.EmailsTestSuite.lambda$static$0(EmailsTestSuite.java:18)
                at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
                at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
                at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
                at com.seanergie.test.EmailsTestSuite.getGreenMail(EmailsTestSuite.java:21)
                at com.seanergie.test.EmailsTestSuite.afterEachTest(EmailsTestSuite.java:36)
```

**Comment by benfortuna** [comment] 2022-05-24 05:15
The dependency has been fixed in all branches (updated to jakarta-mail:2.0.1), hope to release v4-beta1 in the next week or so.

**Comment by BigMichi1** [comment] 2022-05-31 10:29
we tried to upgrade today to 3.2.3 and now our build is failing because we are using "still" version 1.6.7 which is the one spring-boot defines. 
just my opinion: i think there should be for the transition period two artefacts published one with "old" (javax) and one with "new" (jakarta) imports or a major version should be released, but still maintain the "old" versions until the major frameworks also have changed. just from the version number (when taking semantic versioning into consideration), there was no breakage expected

**Comment by benfortuna** [comment] 2022-05-31 14:28
Ah, that is unfortunate. I guess the problem is caused by how JavaMail uses service loader to "discover" the providers, so it makes it difficult to support both libraries in the same classpath.

Instead of trying to support either I think we will just remove the javamail dependency completely. The only reason it was added was to validate the `EMAIL` parameter, but I think that is not enough benefit to keep it.

I will remove this dependency and release a new version shortly.

**Closed** 2022-08-07 01:26 UTC
