### ISSUE TITLE
NPE when a line contains only colon sign

### ISSUE THREAD

**Issue by lyman** [ical4j/ical4j#139] opened 2017-04-23 14:26 UTC
ical4j will throw a NPE when an event contains a line contains only colon sign. I'm not sure 
if this is malformed regards to corresponding RFC, unfortunately, the caldav implementation my company has chosen will deliver such ics texts.

Here's a sample and Mozilla Thunderbird is tolerant with such cases.

```
BEGIN:VEVENT
CLASS:
CREATED:20121015T070600Z
DTSTART:20121018T020000Z
LAST-MODIFIED:20140815T175058Z
LOCATION:somewhere
ORGANIZER;CN=somesystem:mailto:foo@bar.com
PRIORITY:5
DTSTAMP:20121015T070600Z
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Scrum Gathering
	Test Automation
TRANSP:TRANSPARENT
UID:a5f13918-e1a8-4035-ac92-44a412315b00
DTEND:20121018T040000Z
ATTENDEE;CN=foo@bar.com;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTI
	CIPANT;RSVP=TRUE:mailto:foo@bar.com;
X-ALT-DESC;FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//E
	N">\n<HTML>\n<HEAD>\n<META NAME="Generator" CONTENT="MS Exchange Server "v
	ersion 08.00.0681.000">\n<TITLE></TITLE>\n</HEAD>\n<BODY>\n<!-- Converted
	from text/rtf format -->\n\n<P DIR=LTR ALIGN=JUSTIFY><SPAN LANG="en-us"><F
	ONT FACE="Times New Roman"><p><img border="0" alt="" src="http://example.com" />
:
:
:
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MS-OLK-CONFTYPE:0
X-MICROSOFT-CDO-ATTENDEE-CRITICAL-CHANGE:20121015T070600Z
X-MICROSOFT-CDO-OWNER-CRITICAL-CHANGE:20121015T070600Z
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
DESCRIPTION:REMINDER
RELATED=START:-PT00H15M00S
END:VALARM
END:VEVENT
```

**Comment by benfortuna** [comment] 2017-04-24 14:25
Hi, I've created a test using your sample and confirmed the issue. I've created a pull request (#140) with a fix that I will merge shortly.

**Comment by lyman** [comment] 2017-04-26 08:09
Thanks! Looking forward to a release with this fix.

**Comment by stellingsimon** [comment] 2017-11-19 15:08
Since PR #140 is merged, I presume this issue could be closed, is that correct?

**Closed** 2017-11-19 21:49 UTC
Labels: bug
