### ISSUE TITLE
different set of transitive dependencies when used with maven and gradle

### ISSUE THREAD

**Issue by BigMichi1** [ical4j/ical4j#494] opened 2021-05-17 07:35 UTC
**Describe the bug**
When we inspected our transitive dependencies in our project we have seen that ical4j 3.0.25 add Groovy and javax.cache as a dependency that is packaged into the runtime classpath

during a deeper investigation, we have seen that when we use ical4j with maven this does not happen

**To Reproduce**
1. create an empty project with maven and add ical4j as a dependency
2. create an empty project with Gradle and add ical4j as a dependency
3. compare dependencies

**Expected behavior**
optional dependencies should not be added when ical4j is used with Gradle

**Screenshots**
Maven
![Bildschirmfoto vom 2021-05-17 09-32-49](https://user-images.githubusercontent.com/91786/118449083-0b6e0580-b6f3-11eb-8453-aa90a9538465.png)

Gradle
![Bildschirmfoto vom 2021-05-17 09-33-35](https://user-images.githubusercontent.com/91786/118449105-12951380-b6f3-11eb-9283-0ced5effe35f.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version 16

**Additional context**

**Comment by Vampire** [comment] 2021-12-02 16:46
Just observed the same, previously using an Ivy mirror of the library where no Gradle Module Metadata is available and now switching to a Maven mirror where it is available and suddenly new dependencies are pulled in.

The problem is the usage of the nebula-optional plugin that just manipulates the generated POM file but does not care to (and is not really able to) manipulate the Gradle Module metadata file.

To properly resolve / model this, you should remove the usage of the nebula optional plugin and instead use the feature variants.
Those feature variants can then be selected nicely with Gradle and thus get the needed dependencies automatically when the respective feature variant is requested and in the POM they will automatically land as `optional` dependencies. 

For more information see for example:
https://blog.gradle.org/optional-dependencies
https://docs.gradle.org/current/userguide/feature_variants.html

**Comment by Vampire** [comment] 2024-04-11 13:44
This is fixed since 3.2.15 by not using the `nebula-optional` plugin anymore but defining proper feature variants.
This issue can be closed as fixed.

**Closed** 2024-04-11 23:05 UTC
