### ISSUE TITLE
Long time to build from a ics file

### ISSUE THREAD

**Issue by pgametys** [ical4j/ical4j#325] opened 2019-04-27 11:37 UTC
**Describe the bug**
I try to read a quite large ics file (1.4Mb, 2400 events) and it takes nearly one minute

**To Reproduce**
I use the java library, version 3.0.6, with this code :

        URL icsUrl = new URL(url);
        HttpURLConnection connexion = (HttpURLConnection)icsUrl.openConnection();

        try (InputStream flux = connexion.getInputStream())
        {  
            CalendarBuilder builder = new CalendarBuilder();
            Calendar calendar = builder.build(flux);
        }

The `builder.build(flux)` takes nearly 1 minute (I tried to download directly the ics file and it takes less than 1sec)

Is there any way to read it faster ?

**Comment by alfonsobonso** [comment] 2019-09-09 14:13
Trying to get closer to this, I am testing with a ics file from my local file system - ~800k, 2500 events
with a similar vanilla config as above.
It seems the changes in 3.0.5 have severely impacted performance.
Average times (ms) to run the builder.build(inputStream):

version  time
3.0.9 86477
3.0.6 89591
3.0.5 90608
3.0.4 501
3.0.1 484

It spends a lot of time in:

> at java.util.Collections$SynchronizedMap.get(Collections.java:2584)
>        - waiting to lock <0x000000008b642ba8> (a java.util.Collections$SynchronizedMap)
>        at net.fortuna.ical4j.model.DateTime$DateFormatCache.get(DateTime.java:544)

and much time in the  construction of java.util.(GregorianCalendar), but I haven't been able to get closer comparing the 3.0.4 and 3.0.5 release code changes

**Comment by functionaldude** [comment] 2020-03-09 12:10
This issue is still not fixed in version 3.0.14, parse times seem to be a lot slower and we get a lot more minor GCs.

**Comment by benfortuna** [comment] 2020-03-09 22:15
Thanks for the update. 

You might like to try parsing your file with the new ical4j 4.0 Alpha release. 

Whilst it may not be a feasible option just yet it might help to identify if the new implementation also suffers from the same issue.

Or it could just create a heap of other issues, but I thought your test should be simple enough just to see how it handles.

**Comment by vonox7** [comment] 2020-03-24 14:34
The issue is still present at 3.0.17.
@benfortuna could you please publish the version to e.g. mavencentral so we can try the new alpha1?

**Comment by benfortuna** [comment] 2020-03-24 20:59
There is a build of 4alpha1 on GitHub packages, although you do need to configure maven with an additional repo. See https://ical4j.github.io for more details.

I will see if I can also publish to maven central.

**Comment by benfortuna** [comment] 2020-03-25 03:36
I've just published a new alpha release to bintray. This should appear in maven central shortly.

https://bintray.com/ical4j/maven/ical4j/4.0.0-alpha2

**Comment by vonox7** [comment] 2020-03-25 18:57
Thanks for pushing it to bintray @benfortuna ! With the 4.0.0-alpha2 version i can confirm that this error is resolved. Both CPU and GC footprint don't indicate any significant differences between 3.0.3 and 4.0.0-alpha2.

Is there a way to backport the fix also to the 3.x branch? Otherwise 3.0.3 is the last recommended version to use (3.0.4 has some bugs that are solved later), as 3.0.5 - 3.0.17 have this major CPU performance problem. Note that our backends main job is not to parse ical feeds, but still we need twice as much containers to handle the increased load that is produced by ical4j version 3.0.5 and 3.0.17.

**Comment by benfortuna** [comment] 2020-03-25 23:50
Ok, so I can confirm there was a refactor of calendar parsing in 3.0.5 that I think is likely to be the cause of the issue. 

Specifically I think it could be related to resolving timezones for TZID parameters. I've done a comparison of 3.04 and 3.0.17 (and 4.0.0-alpha) with regard to resolving custom timezones.

**3.0.4**

* Any property with a TZID parameter with an unrecognized timezone (i.e. it may be defined later in the parsed object) is added to a list
* After parsing, the list of properties with unrecognized timezones is checked again for available timezones (i.e. single iteration of list) and updated

**3.0.17**

* Any TZID parameter is added to a list to be checked for timezones after parsing
* After parsing, ALL properties are iterated for EACH TZID to find which one the TZID param belongs to and updates the timezone if available

Obviously this is going to be pretty intensive where there are a lot of properties. The reason for the change is the introduction of deferred build of properties when parsing, but I think I can improve the implementation to return to a single iteration of the property list.

NOTE: The reason `4.0.0-alpha` isn't affected is we moved the timezone resolution completely out of parsing as it is lazily resolved in the TZID param itself.


`3.0.4`:

```java
        public void parameter(final String name, final String value) throws URISyntaxException {
            ...
            if (param instanceof TzId && tzRegistry != null && !(property instanceof XProperty)) {
                final TimeZone timezone = tzRegistry.getTimeZone(param.getValue());
                if (timezone != null) {
                    updateTimeZone(property, timezone);
                } else {
                    // VTIMEZONE may be defined later, so so keep
                    // track of dates until all components have been
                    // parsed, and then try again later
                    datesMissingTimezones.add(property);
                }
            }
        }

    private void resolveTimezones()
            throws IOException {

        // Go through each property and try to resolve the TZID.
        for (Property property : datesMissingTimezones) {
            final Parameter tzParam = property.getParameter(Parameter.TZID);
               /* Resolve timezone */
            }
        }
    }

```

`3.0.17`:

```java
    public void parameter(String name, String value) throws URISyntaxException {
        ...
        if (parameter instanceof TzId && tzRegistry != null) {
            // VTIMEZONE may be defined later, so so keep
            // track of dates until all components have been
            // parsed, and then try again later
            propertiesWithTzId.add((TzId) parameter);
        }

        propertyBuilder.parameter(parameter);
    }

    private void resolveTimezones(List<Property> properties) throws IOException {

        // Go through each property and try to resolve the TZID.
        for (TzId tzParam : propertiesWithTzId) {
                /* Resolve timezone */
            }
        }
    }

    public void endCalendar() throws IOException {
        if (propertiesWithTzId.size() > 0 && tzRegistry != null) {
            for (CalendarComponent component : calendar.getComponents()) {
                resolveTimezones(component.getProperties());

                if (component instanceof VAvailability) {
                    for (Component available : ((VAvailability) component).getAvailable()) {
                        resolveTimezones(available.getProperties());
                    }
                } else if (component instanceof VEvent) {
                    for (Component alarm : ((VEvent) component).getAlarms()) {
                        resolveTimezones(alarm.getProperties());
                    }
                } else if (component instanceof VToDo) {
                    for (Component todo : ((VToDo) component).getAlarms()) {
                        resolveTimezones(todo.getProperties());
                    }
                }
            }
        }
        consumer.accept(calendar);
    }

```

**Comment by benfortuna** [comment] 2020-03-26 02:15
PR here: #406

**Comment by vonox7** [comment] 2020-03-26 08:23
Thanks @benfortuna! 3.0.18 fixes now this issue, both CPU and GC levels are back to the state as it was with version 3.0.4! Thank you for the fast fix!

**Closed** 2021-07-25 04:39 UTC
Labels: in review
