### ISSUE TITLE
Exception in thread "main" net.fortuna.ical4j.data.ParserException: Error at line 25:null

### ISSUE THREAD

**Issue by pussbb** [ical4j/ical4j#84] opened 2016-06-02 09:01 UTC
``` java
    String cal2 = "BEGIN:VCALENDAR\n" +
                "CALSCALE:GREGORIAN\n" +
                "PRODID:-//xxxx//xxxxxx//EN\n" +
                "VERSION:2.0\n" +
                "BEGIN:VTIMEZONE\n" +
                "TZID:(GMT-03:00)\n" +
                "BEGIN:STANDARD\n" +
                "DTSTART:16010101T230000\n" +
                "TZOFFSETFROM:-0200\n" +
                "TZOFFSETTO:-0300\n" +
                "RRULE:FREQ=YEARLY;BYDAY=3SU;BYMONTH=2\n" +
                "END:STANDARD\n" +
                "BEGIN:DAYLIGHT\n" +
                "TZOFFSETFROM:-0300\n" +
                "TZOFFSETTO:-0200\n" +
                "RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=10\n" +
                "END:DAYLIGHT\n" +
                "END:VTIMEZONE\n" +
                "BEGIN:VEVENT\n" +
                "UID:1047216278.801463535396580.JavaMail.root(a)xxxx.xxxxx.xxxx\n" +
                "LAST-MODIFIED:20160519T090547Z\n" +
                "DTSTAMP:20160519T090547Z\n" +
                "DTSTART;TZID=\"(GMT-03:00)\":20160518T123000\n" +
                "DTEND;TZID=\"(GMT-03:00)\":20160518T133000\n" +
                "X-MICROSOFT-CDO-ALLDAYEVENT:FALSE\n" +
                "X-MICROSOFT-CDO-IMPORTANCE:1\n" +
                "PRIORITY:5\n" +
                "TRANSP:OPAQUE\n" +
                "X-MICROSOFT-CDO-BUSYSTATUS:BUSY\n" +
                "SEQUENCE:0\n" +
                "SUMMARY:xxxxxxx S-xxxxx\n" +
                "X-SCALIX-LABEL:0\n" +
                "CLASS:PUBLIC\n" +
                "END:VEVENT\n" +
                "END:VCALENDAR\n";
        System.setProperty("ical4j.parsing.relaxed", "true");
        System.setProperty("ical4j.validation.relaxed", "true");
        System.setProperty("ical4j.compatibility.outlook", "true");
        System.setProperty("ical4j.compatibility.notes", "true");
        System.setProperty("ical4j.unfolding.relaxed", "true");
        System.setProperty("net.fortuna.ical4j.timezone.update.enabled", "true");

        System.out.println(cal2);
        InputStream stream = new ByteArrayInputStream(cal2.getBytes(StandardCharsets.UTF_8));
        CalendarBuilder builder = new CalendarBuilder();
        Calendar calendar = null;

        calendar = builder.build(stream);
```

result 

``` console
Jun 02, 2016 11:54:33 AM net.fortuna.ical4j.util.Configurator <clinit>
INFO: ical4j.properties not found.
Exception in thread "main" net.fortuna.ical4j.data.ParserException: Error at line 23:null
    at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:148)
    at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:210)
    at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:191)
    at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:179)
    at com.company.Main.main(Main.java:545)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NullPointerException
    at net.fortuna.ical4j.model.component.Observance.getLatestOnset(Observance.java:169)
    at net.fortuna.ical4j.model.component.VTimeZone.getApplicableObservance(VTimeZone.java:314)
    at net.fortuna.ical4j.model.TimeZone.inDaylightTime(TimeZone.java:137)
    at java.util.TimeZone.getOffsets(TimeZone.java:234)
    at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2800)
    at java.util.Calendar.updateTime(Calendar.java:3393)
    at java.util.Calendar.getTimeInMillis(Calendar.java:1782)
    at java.util.Calendar.getTime(Calendar.java:1755)
    at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1532)
    at java.text.DateFormat.parse(DateFormat.java:364)
    at net.fortuna.ical4j.model.DateTime.setTime(DateTime.java:397)
    at net.fortuna.ical4j.model.DateTime.<init>(DateTime.java:303)
    at net.fortuna.ical4j.model.property.DateProperty.setValue(DateProperty.java:142)
    at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.propertyValue(CalendarBuilder.java:318)
    at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:249)
    at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1(CalendarParserImpl.java:200)
    at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:178)
    at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:390)
    at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$1(CalendarParserImpl.java:376)
    at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:175)
    at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:125)
    ... 9 more

```

expected at least CalendarParserException for e.g. but not NullPointerException.

as workaround 

``` java
cal2.replaceAll(";TZID=\"\\((.*)\\)\"", ";TZID=\"$1\"");
```

it will replace

``` plain
DTSTART;TZID=\"(GMT-03:00)\":20160518T123000
```

to

``` plain
"DTSTART;TZID="GMT-03:00":20160518T123000
```

or it will work if add a space

``` plain
DTSTART;TZID="(GMT-03:00)     ":20160518T123000 
```

**Comment by benfortuna** [comment] 2016-06-07 10:17
Hi,

What version of ical4j are you using? Looking at the latest code there shouldn't be a NullPointerException at the line specified by the stack trace..

**Comment by pussbb** [comment] 2016-06-07 10:24
ical4j version is 1.0.7 .

**Comment by benfortuna** [comment] 2016-07-04 13:29
I've had a look at this issue and the problem isn't caused by the TZID, but actually the DAYLIGHT component missing a DTSTART property, i.e:

```
"BEGIN:DAYLIGHT\n" +
"TZOFFSETFROM:-0300\n" +
"TZOFFSETTO:-0200\n" +
"RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=10\n" +
"END:DAYLIGHT\n" +
```

I'm considering two options to handle this better; one is to validate the timezone when it is parsed (and throw a ValidationException if invalid), and the other it to throw an exception at the point of timezone use. Both of these have quite an impact on method signatures so I'll work on finding the best solution with minimal impact.

regards,
ben

**Comment by benfortuna** [comment] 2016-07-04 14:14
For now the exception will be logged so it doesn't affect method signatures. See #92 and #93 for fixes

**Comment by benfortuna** [comment] 2018-11-23 22:45
Closing ticket with workaround, reopen if still an issue.

**Closed by benfortuna** 2018-11-23 22:45 UTC
Labels: bug
